version: '3.2'
services:
  sync:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/sync
    deploy:
      replicas: 1
      replicas: 2
    networks:
      - arcms
    ports:
      - 8080:8080
  admin:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/admin
    deploy:
      replicas: 2
      update_config:
        delay: 5s
    networks:
      - arcms
    # ports:
    #   - 8090:8090
  portal:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/portal
    deploy:
      replicas: 1
      update_config:
        delay: 5s
    networks:
      - arcms
    ports:
      - 8070:8070
networks:
  arcms:
    driver: overlay
