version: '3.2'
services:
  admin:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/admin
    deploy:
      replicas: 1
      update_config:
        delay: 5s
    networks:
      - arcms
    # ports:
    #   - 8211:8211
  auth:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/auth
    deploy:
      replicas: 1
      update_config:
        delay: 5s
    networks:
      - arcms
    # ports:
    #   - 8212:8212

  portal:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/portal
    deploy:
      replicas: 1
      update_config:
        delay: 5s
    networks:
      - arcms
    # ports:
    #   - 8213:8213

  publish:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/publish
    deploy:
      replicas: 1
      update_config:
        delay: 5s
    networks:
      - arcms
    # ports:
    #   - 8214:8214

  sync:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/sync
    deploy:
      replicas: 1
    networks:
      - arcms
    # ports:
    #   - 8215:8215



  web:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/web
    deploy:
      replicas: 1
      update_config:
        delay: 5s
    networks:
      - arcms
    # ports:
    #   - 8216:8216

  meta:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/meta
    deploy:
      replicas: 1
      update_config:
        delay: 5s
    networks:
      - arcms
    ports:
      - 8222:8222


networks:
  arcms:
    driver: overlay
