version: '3.2'
services:
  sync:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/sync
    deploy:
      replicas: 2
    networks:
      - arcms
    ports:
      - 8080:8080
  admin:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/admin
    deploy:
      replicas: 1
      update_config:
        delay: 5s
    networks:
      - arcms
    # ports:
    #   - 8090:8090
  portal:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/portal
    deploy:
      replicas: 1
      update_config:
        delay: 5s
    networks:
      - arcms
    ports:
      - 8070:8070
  publish:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/publish
    deploy:
      replicas: 1
      update_config:
        delay: 5s
    networks:
      - arcms
    ports:
      - 8071:8071
  web:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/web
    deploy:
      replicas: 1
      update_config:
        delay: 5s
    networks:
      - arcms
    ports:
      - 8072:8072
  auth:
    image: registry.cn-hangzhou.aliyuncs.com/mengstars/auth
    deploy:
      replicas: 1
      update_config:
        delay: 5s
    networks:
      - arcms
    ports:
      - 8073:8073
networks:
  arcms:
    driver: overlay
